= https://github.com/input-output-hk/marlowe-playground[Marlowe Playground]
:email: plutus@iohk.io
:author: Input Output HK Limited
:toc: left
:reproducible:

Marlowe is a platform for financial products as smart contracts. Marlowe Playground is
a development tool that helps build and simulate Marlowe Contracts.

Related projects:

* https://github.com/input-output-hk/marlowe[Marlowe]: Marlowe language specification
* https://github.com/input-output-hk/marlowe-cardano[Marlowe Cardano]: Implementation of the Marlowe Language for the Cardano Blockchain. Also haskell lib.
* https://github.com/input-output-hk/purescript-marlowe[PureScript Marlowe]: PureScript implementation of the Marlowe language for the Cardano Blockchain.


[IMPORTANT]
====
The rest of this README is focussed on people who want to develop or contribute to Marlowe.

== Documentation

== Working with the project

=== How to submit an issue

Issues can be filed in the https://github.com/input-output-hk/marlowe-playground/issues[GitHub Issue tracker].

[[how-to-develop]]
=== How to develop and contribute to the project

See link:CONTRIBUTING{outfilesuffix}[CONTRIBUTING], which describes our processes in more detail including development environments.

=== How to build the project's artifacts

This section contains information about how to build the project's artifacts for independent usage.
For development work see <<how-to-develop>> for more information.

[[prerequisites]]

==== Prerequisites

The Haskell libraries in the Marlowe project are built with `cabal` and Nix.
The other artifacts (docs etc.) are also most easily built with Nix.

===== Nix

This repository uses nix to provide the development and build environment.

If you know nix, simply run `nix develop` to enter the shell; if prompted, trust 
the flake config values to enable access to our binary caches.   

The nix code is based on a template from the the 
[IOGX flake](https://github.com/input-output-hk/iogx). 
For instructions on how to install and configure nix (including how to enable 
access to our binary caches), and how keep the flake inputs up to date, refer to 
[this section](https://github.com/input-output-hk/iogx/blob/main/doc/api.md#flakenix)
of the IOGX manual.

===== Non-Nix

You can build some of the Haskell packages without Nix, but this is not recommended and we don't guarantee that these prerequisites are sufficient.
If you use Nix, these tools are provided for you via `shell.nix`, and you do *not* need to install them yourself.

* If you want to build our Haskell packages with https://www.haskell.org/cabal/[`cabal`], then install it.
* If you want to build our Haskell packages with https://haskellstack.org/[`stack`], then install it.

[NOTE]
====
For fresh development setups, you also need to run `cabal update`.
====

Run `cabal build all` from the root to build all artifacts.

=== Deployment

The Marlowe Playground is automatically deployed upon certain pushes to GitHub

* https://marlowe-playground-staging.plutus.aws.iohkdev.io/[Marlowe Playground staging] and https://marlowe-run-staging.plutus.aws.iohkdev.io/[Marlowe Run staging] are deployed from every commit pushed to `main` (these URLs subject to change)

For more details, including instructions for setting up ad hoc testing deployments, see https://github.com/input-output-hk/plutus-ops[the plutus-ops repo].

== Licensing

You are free to copy, modify, and distribute Marlowe under the terms
of the Apache 2.0 license. See the link:./LICENSE[LICENSE]
and link:./NOTICE[NOTICE] files for details.
