apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: marlowe-playground-test
  namespace: marlowe-staging
  annotations:
    app.oam.dev/publishVersion: 0.0.12
spec:
  components:
  - name: marlowe-playground-test
    type: webservice
    properties:
      cpu: "0.5"
      image: ghcr.io/input-output-hk/marlowe-playground-server:latest
      args:
      - webserver
      env:
      - name: FRONTEND_URL
        value: https://marlowe-playground-test.scdev.aws.iohkdev.io
      - name: WEBGHC_URL
        value: http://localhost:8080
      - name: JWT_SIGNATURE
        valueFrom:
          secretKeyRef:
            key: JWT_SIGNATURE
            name: jwt-signature
      - name: GITHUB_CLIENT_ID
        valueFrom:
          secretKeyRef:
            key: clientID
            name: gh-oauth
      - name: GITHUB_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            key: clientSecret
            name: gh-oauth
      - name: GITHUB_CALLBACK_PATH
        valueFrom:
          secretKeyRef:
            key: callbackPath
            name: gh-oauth
      imagePullPolicy: Always
      memory: 1024Mi
      ports:
      - expose: true
        port: 8080
        protocol: TCP
    traits:
    - properties:
        replicas: 1
      type: scaler
    - properties:
        domains:
        - marlowe-playground-test.scdev.aws.iohkdev.io
        rules:
        - path:
            type: PathPrefix
            value: /api
          port: 8080
      type: https-route
  - name: marlowe-playground-client-test
    type: webservice
    properties:
      cpu: "0.5"
      image: p3terx/darkhttpd
      args:
      - /client-www
      - --port 8080
      imagePullPolicy: Always
      memory: 1024Mi
      ports:
      - expose: true
        port: 8080
        protocol: TCP
    traits:
    - properties:
        replicas: 1
      type: scaler
    - properties:
        domains:
        - marlowe-playground-test.scdev.aws.iohkdev.io
        rules:
        - port: 8080
      type: https-route
    - type: init-container
      properties:
        name: build-client
        image: nixos/nix
        cmd:
        - nix
        - build
        - "github:input-output-hk/marlowe-playground/#marlowe-playground-client"
        - -o /client-www
        mountName: client-www
        initMountPath: /client-www
        appMountPath: /client-www

  policies:
  - name: local-marlowe-staging
    properties:
      clusters:
      - local
      namespace: marlowe-staging
    type: topology

  - name: local-marlowe-production
    properties:
      clusters:
      - local
      namespace: marlowe-production
    type: topology

  - name: override-marlowe-production
    type: override
    properties:
      components:
      - name: marlowe-playground-test
        properties:
          env:
          - name: FRONTEND_URL
            value: https://marlowe-playground-test-prod.scdev.aws.iohkdev.io
          - name: WEBGHC_URL
            value: http://localhost:8080
          - name: JWT_SIGNATURE
            valueFrom:
              secretKeyRef:
                key: JWT_SIGNATURE
                name: jwt-signature
          - name: GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: clientID
                name: gh-oauth-production
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: clientSecret
                name: gh-oauth-production
          - name: GITHUB_CALLBACK_PATH
            valueFrom:
              secretKeyRef:
                key: callbackPath
                name: gh-oauth-production
          image: ghcr.io/input-output-hk/marlowe-playground-server:2023-05-30-e2d5fd6
        traits:
        - properties:
            domains:
            - marlowe-playground-test-prod.scdev.aws.iohkdev.io
            rules:
            - path:
                type: PathPrefix
                value: /api
              port: 8080
          type: https-route
      - name: marlowe-playground-client-test
        properties:
          image: ghcr.io/input-output-hk/marlowe-playground-client:2023-05-30-e2d5fd6
        traits:
        - properties:
            domains:
            - marlowe-playground-test-prod.scdev.aws.iohkdev.io
            rules:
            - port: 8080
          type: https-route
  workflow:
    mode:
      steps: StepByStep
    steps:
    - meta:
        alias: Push server image
      name: push-server-image
      type: build-push-image-configurable
      properties:
        context:
          git: github.com/input-output-hk/sc-dev-platform
          branch: bpi-resource-config
        image: ghcr.io/input-output-hk/marlowe-playground-server:latest
        dockerfile: infra/nix-docker-builder/Dockerfile
        credentials:
          image:
            name: iohk-ghcr-creds
        requests:
          ephemeralStorage: 20Gi
        singleSnapshot: true
        buildArgs:
        - "INCLUDED_FLAKE_URIS=github:input-output-hk/marlowe-playground#marlowe-playground-server github:input-output-hk/marlowe-playground#ghc-with-marlowe nixpkgs#coreutils nixpkgs#cacert"
        - "ENTRYPOINT_BIN_NAME=marlowe-playground-server"
    - meta:
        alias: Deploy To local-marlowe-staging
      name: local-marlowe-staging
      properties:
        policies:
        - local-marlowe-staging
      type: deploy
    - meta:
        alias: Deploy To local-marlowe-production
      name: local-marlowe-production
      properties:
        policies:
        - local-marlowe-production
        - override-marlowe-production
      type: deploy
