{ inputs, cell }:
let
  inherit (cell.library) pkgs;
  inherit (cell.packages) generated-purescript;

in

pkgs.runCommand "generated-purescript-test" { buildInputs = [ pkgs.diffutils pkgs.glibcLocales ]; } ''
  set +e
  cp -a ${inputs.self} expected
  cp -a ${inputs.self} actual
  chmod -R +w actual
  rm -rf actual/marlowe-playground-client/generated
  cp -a ${generated-purescript} actual/marlowe-playground-client/generated
  diff --brief --recursive expected actual
  EXIT_CODE=$?
  if [[ $EXIT_CODE != 0 ]]
  then
    mkdir -p $out/nix-support
    diff -ur expected actual > $out/actual.diff
    echo "file none $out/actual.diff" > $out/nix-support/hydra-build-products
    echo "*** actual found changes that need addressed first"
    echo "*** Please run \`generate-purs\` and commit changes."
    echo "*** or apply the diff generated by hydra if you don't have nix."
    exit $EXIT_CODE
  else
    echo $EXIT_CODE > $out
  fi
''
