name: "E2E Tests"
on:
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
          cache: 'npm'
      - name: Update npm
        run: npm install -g npm@8.19.2
      - name: Debugging Information
        run: |
          nix --version
          node --version
          npm --version
          which cucumber-js
          npm list -g
      - name: Run E2E tests
        run: |
          nix develop --command bash -c 'cd e2e && npm install && . ./run_tests.sh @dev'
